# Generated by Django 4.2.21 on 2025-05-27 13:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dailytracks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pdca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_date', models.DateField(help_text='週の開始日（例: 月曜）')),
                ('plan', models.TextField(max_length=1000)),
                ('execution', models.TextField(max_length=1000)),
                ('review', models.TextField(max_length=1000)),
                ('action', models.TextField(max_length=1000)),
                ('feedback', models.TextField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='pdca',
            constraint=models.UniqueConstraint(fields=('user', 'week_date'), name='unique_user_week'),
        ),
    ]
