# Generated by Django 4.2.21 on 2025-05-29 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailytracks', '0003_oneonone_oneonone_unique_user_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oneonone',
            name='feedback',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='oneonone',
            name='next_action',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
