# Generated by Django 4.2.21 on 2025-05-29 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dailytracks', '0004_alter_oneonone_feedback_alter_oneonone_next_action'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oneonone',
            old_name='last_actions',
            new_name='last_action',
        ),
    ]
