# Generated by Django 4.2.21 on 2025-05-30 03:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dailytracks', '0005_rename_last_actions_oneonone_last_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GoalActionPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.TextField(max_length=1000)),
                ('action', models.TextField(max_length=1000)),
                ('result', models.TextField(blank=True, max_length=1000)),
                ('feedback', models.TextField(blank=True, max_length=1000)),
                ('goal_setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_actions', to='dailytracks.goalsetting')),
            ],
        ),
        migrations.AddConstraint(
            model_name='goalsetting',
            constraint=models.UniqueConstraint(fields=('user', 'month'), name='unique_user_monthly_goal'),
        ),
    ]
